//actionTypes.js
export default {

    POST_POSTAUTHENDICATION_REQUEST:'POST_POSTAUTHENDICATION_REQUEST',
    POST_POSTAUTHENDICATION_SUCCESS:'POST_POSTAUTHENDICATION_SUCCESS',
    POST_POSTAUTHENDICATION_FAILURE:'POST_POSTAUTHENDICATION_FAILURE',
    POST_POSTAUTHENDICATION_FAILURE_INVALID:'POST_POSTAUTHENDICATION_FAILURE_INVALID', 

   POST_CREATEVISIT_REQUEST: "POST_CREATEVISIT_REQUEST",
  POST_CREATEVISIT_SUCCESS: "POST_CREATEVISIT_SUCCESS",
  POST_CREATEVISIT_FAILURE: "POST_CREATEVISIT_FAILURE",
  POST_CREATEVISIT_FAILURE_INVALID: "POST_CREATEVISIT_FAILURE_INVALID",

    ODOO_CALL_REQUEST: 'ODOO_CALL_REQUEST',
    ODOO_CALL_SUCCESS: 'ODOO_CALL_SUCCESS',
    ODOO_CALL_FAILURE: 'ODOO_CALL_FAILURE',
    
}